"""add qlearning state fields

Revision ID: 2f38a24fbd30
Revises: 
Create Date: 2025-09-18 13:06:18.374431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f38a24fbd30'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mslq_level', sa.Enum('high', 'medium', 'low'), nullable=True))
        batch_op.add_column(sa.Column('ams_type', sa.Enum('intrinsic', 'extrinsic', 'achievement', 'amotivation'), nullable=True))
        batch_op.add_column(sa.Column('engagement_level', sa.Enum('high', 'medium', 'low'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.drop_column('engagement_level')
        batch_op.drop_column('ams_type')
        batch_op.drop_column('mslq_level')

    # ### end Alembic commands ###
